DETECTION_TO_QOZ_INCIDENT = {
    "person": "person",
    "phone": "phone_usage",
    "phone_usage": "phone_usage",
    "baggage": "lost_property",
    "mass_gathering": "crowd",
    "crowd": "crowd",
    "fight": "fight",
    "weapon": "weapon",
    "fall": "fall",
    "smoking": "smoking",
    "sleep": "sleep",
    "sleeping": "sleep",
    "fire": "fire",
    "smoke": "smoke",
    "anpr": "anpr",
    "license_plate": "anpr",
    "climbing_fence": "fence_climbing",
    "fence_climbing": "fence_climbing",
    "climbing": "fence_climbing",
    "fighting": "fight",
    "fallen": "fall",
    "intrusion": "crowd",
}

INCIDENT_ALERT = {
    "phone_usage": ("phone_usage", "Student using phone in class", "warning"),
    "lost_property": ("forgotten_object", "Potential forgotten bag/object left unattended", "warning"),
    "crowd": ("mass_gathering", "Mass gathering detected", "warning"),
    "fight": ("conflict", "Potential conflict/fight detected", "critical"),
    "weapon": ("weapon", "Weapon detected", "critical"),
    "fall": ("fall", "Potential fall detected", "critical"),
    "smoking": ("smoking", "Smoking detected", "warning"),
    "sleep": ("sleeping", "Student sleeping in classroom", "warning"),
    "fire": ("fire", "Fire detected", "critical"),
    "smoke": ("smoke", "Smoke detected", "critical"),
    "anpr": ("anpr", "Vehicle plate detected in restricted zone", "warning"),
    "fence_climbing": ("perimeter_breach", "Student climbing perimeter fence", "critical"),
}

