services:
  vision:
    build:
      context: ./vision
      dockerfile: Dockerfile
    image: qoz-offline-vision:latest

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: qoz-offline-backend:latest

  web:
    build:
      context: ./web
      dockerfile: ../Dockerfile.web
    image: qoz-offline-web:latest

